<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-ios;net9.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>
		<TargetAndroidVersion>35</TargetAndroidVersion>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net8.0-tizen</TargetFrameworks> -->

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>CS.ERP_MOB</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>Ova SSM</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.ovaerp.cs.erp_mob_ssm</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">13.1</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
	</PropertyGroup>

<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-android|AnyCPU'">
  <AndroidPackageFormat>aab</AndroidPackageFormat>
  <DebugSymbols>True</DebugSymbols>
  <AndroidKeyStore>False</AndroidKeyStore>
  <AndroidUseAapt2>True</AndroidUseAapt2>
  <AndroidCreatePackagePerAbi>False</AndroidCreatePackagePerAbi>
</PropertyGroup>

<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-android|AnyCPU'">
  <EmbedAssembliesIntoApk>False</EmbedAssembliesIntoApk>
  <AndroidKeyStore>False</AndroidKeyStore>
  <AndroidUseAapt2>True</AndroidUseAapt2>
  <AndroidCreatePackagePerAbi>False</AndroidCreatePackagePerAbi>
  <AndroidPackageFormat>aab</AndroidPackageFormat>
</PropertyGroup>

<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-ios|AnyCPU'">
  <MtouchLink>None</MtouchLink>
</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\ssmsplash.png" Color="#FFFFFF" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="ViewsModel\.DS_Store" />
	  <None Include="Views\.DS_Store" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="CHARS.HR.BOL">
	    <HintPath>Libraries\CHARS.HR.BOL.dll</HintPath>
	  </Reference>
	  <Reference Include="CS.ERP.BOL">
	    <HintPath>Libraries\CS.ERP.BOL.dll</HintPath>
	  </Reference>
	  <Reference Include="CS.ERP.EML">
	    <HintPath>Libraries\CS.ERP.EML.exe</HintPath>
	  </Reference>
	  <Reference Include="CS.ERP.PL">
	    <HintPath>Libraries\CS.ERP.PL.dll</HintPath>
	  </Reference>
	  <Reference Include="Newtonsoft.Json">
	    <HintPath>Libraries\Newtonsoft.Json.dll</HintPath>
	  </Reference>
	  <Reference Include="stdole">
	    <HintPath>Libraries\stdole.dll</HintPath>
	  </Reference>
	  <Reference Include="Stripe.net">
	    <HintPath>Libraries\Stripe.net.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="akgul.Maui.DataGrid" Version="4.0.5" />
		<PackageReference Include="CommunityToolkit.Maui" Version="9.1.1" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
		<PackageReference Include="FreshMvvm.Maui" Version="0.0.4" />
		<!-- <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0-rc.1.24431.7" /> -->
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
		<PackageReference Include="Microsoft.Identity.Client" Version="4.66.1" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.0-rc.1.24431.7" />
		<PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform" Version="6.2.14" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="RGPopup.Maui" Version="1.2.1" />
		<PackageReference Include="SQLite" Version="3.13.0" />
		<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
		<PackageReference Include="Syncfusion.Maui.Core" Version="30.2.6" />
  		<PackageReference Include="Syncfusion.Maui.Scheduler" Version="30.2.6" />
  		<PackageReference Include="Syncfusion.Maui.DataGrid" Version="30.2.6" />
		<PackageReference Include="Syncfusion.Maui.Popup" Version="30.2.6" />
		<PackageReference Include="Syncfusion.Maui.TabView" Version="30.2.6" />
		<PackageReference Include="Syncfusion.Maui.Charts" Version="30.2.6" />
		<PackageReference Include="System.Private.Uri" Version="4.3.2" />
		<PackageReference Include="TouchEffect.Maui" Version="7.0.0" />
		<PackageReference Include="UraniumUI" Version="2.12.1" />
		<PackageReference Include="UraniumUI.Material" Version="2.12.1" />
	</ItemGroup>


	<ItemGroup>
	  <AndroidResource Remove="Services\WMS\**" />
	  <AndroidResource Remove="ViewsModel\ATT\**" />
	  <AndroidResource Remove="ViewsModel\CRM\**" />
	  <AndroidResource Remove="ViewsModel\HCM\**" />
	  <AndroidResource Remove="ViewsModel\PAY\**" />
	  <!-- <AndroidResource Remove="ViewsModel\POS\**" /> -->
	  <AndroidResource Remove="Views\ATT\**" />
	  <AndroidResource Remove="Views\CRM\**" />
	  <AndroidResource Remove="Views\HCM\**" />
	  <AndroidResource Remove="Views\NewFolder1\**" />
	  <AndroidResource Remove="Views\NewFolder2\**" />
	  <AndroidResource Remove="Views\PAY\**" />
	  <!-- <AndroidResource Remove="Views\POS\**" /> -->
	  <Compile Remove="Services\WMS\**" />
	  <Compile Remove="ViewsModel\ATT\**" />
	  <Compile Remove="ViewsModel\CRM\**" />
	  <Compile Remove="ViewsModel\HCM\**" />
	  <Compile Remove="ViewsModel\PAY\**" />
	  <!-- <Compile Remove="ViewsModel\POS\**" /> -->
	  <Compile Remove="Views\ATT\**" />
	  <Compile Remove="Views\CRM\**" />
	  <Compile Remove="Views\HCM\**" />
	  <Compile Remove="Views\NewFolder1\**" />
	  <Compile Remove="Views\NewFolder2\**" />
	  <Compile Remove="Views\PAY\**" />
	  <!-- <Compile Remove="Views\POS\**" /> -->
	  <EmbeddedResource Remove="Services\WMS\**" />
	  <EmbeddedResource Remove="ViewsModel\ATT\**" />
	  <EmbeddedResource Remove="ViewsModel\CRM\**" />
	  <EmbeddedResource Remove="ViewsModel\HCM\**" />
	  <EmbeddedResource Remove="ViewsModel\PAY\**" />
	  <!-- <EmbeddedResource Remove="ViewsModel\POS\**" /> -->
	  <EmbeddedResource Remove="Views\ATT\**" />
	  <EmbeddedResource Remove="Views\CRM\**" />
	  <EmbeddedResource Remove="Views\HCM\**" />
	  <EmbeddedResource Remove="Views\NewFolder1\**" />
	  <EmbeddedResource Remove="Views\NewFolder2\**" />
	  <EmbeddedResource Remove="Views\PAY\**" />
	  <!-- <EmbeddedResource Remove="Views\POS\**" /> -->
	  <MauiCss Remove="Services\WMS\**" />
	  <MauiCss Remove="ViewsModel\ATT\**" />
	  <MauiCss Remove="ViewsModel\CRM\**" />
	  <MauiCss Remove="ViewsModel\HCM\**" />
	  <MauiCss Remove="ViewsModel\PAY\**" />
	  <!-- <MauiCss Remove="ViewsModel\POS\**" /> -->
	  <MauiCss Remove="Views\ATT\**" />
	  <MauiCss Remove="Views\CRM\**" />
	  <MauiCss Remove="Views\HCM\**" />
	  <MauiCss Remove="Views\NewFolder1\**" />
	  <MauiCss Remove="Views\NewFolder2\**" />
	  <MauiCss Remove="Views\PAY\**" />
	  <!-- <MauiCss Remove="Views\POS\**" /> -->
	  <MauiXaml Remove="Services\WMS\**" />
	  <MauiXaml Remove="ViewsModel\ATT\**" />
	  <MauiXaml Remove="ViewsModel\CRM\**" />
	  <MauiXaml Remove="ViewsModel\HCM\**" />
	  <MauiXaml Remove="ViewsModel\PAY\**" />
	  <!-- <MauiXaml Remove="ViewsModel\POS\**" /> -->
	  <MauiXaml Remove="Views\ATT\**" />
	  <MauiXaml Remove="Views\CRM\**" />
	  <MauiXaml Remove="Views\HCM\**" />
	  <MauiXaml Remove="Views\NewFolder1\**" />
	  <MauiXaml Remove="Views\NewFolder2\**" />
	  <MauiXaml Remove="Views\PAY\**" />
	  <!-- <MauiXaml Remove="Views\POS\**" /> -->
	  <None Remove="Services\WMS\**" />
	  <None Remove="ViewsModel\ATT\**" />
	  <None Remove="ViewsModel\CRM\**" />
	  <None Remove="ViewsModel\HCM\**" />
	  <None Remove="ViewsModel\PAY\**" />
	  <!-- <None Remove="ViewsModel\POS\**" /> -->
	  <None Remove="Views\ATT\**" />
	  <None Remove="Views\CRM\**" />
	  <None Remove="Views\HCM\**" />
	  <None Remove="Views\NewFolder1\**" />
	  <None Remove="Views\NewFolder2\**" />
	  <None Remove="Views\PAY\**" />
	  <!-- <None Remove="Views\POS\**" /> -->
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="Route\Att_Route.cs" />
	  <Compile Remove="Route\Crm_Route.cs" />
	  <Compile Remove="Route\Hcm_Route.cs" />
	  <Compile Remove="Route\Pay_Route.cs" />
	  <Compile Remove="Route\Wms_Route.cs" />
	  <Compile Remove="ViewsModel\Frame\VmlDiscussion.cs" />
	  <Compile Remove="Views\Frame\PopCheckOut.xaml.cs" />
	  <Compile Remove="Views\Frame\PopLiveChat.xaml.cs" />
	  <Compile Remove="Views\Frame\PopStockDetail.xaml.cs" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Remove="Views\Frame\PopCheckOut.xaml" />
	  <MauiXaml Remove="Views\Frame\PopLiveChat.xaml" />
	  <MauiXaml Remove="Views\Frame\PopStockDetail.xaml" />
	</ItemGroup>
	
	<ItemGroup>
		<Folder Include="Models\" />
		<Folder Include="Resources\Messages\" />
		<Folder Include="Services\ACC\" />
		<Folder Include="DB\" />
		<Folder Include="ViewsModel\POS\" />
	</ItemGroup>
	
	<ItemGroup>
	  <Compile Update="Views\Frame\FrmSsmItemCard.xaml.cs">
	    <DependentUpon>FrmSsmItemCard.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\SSM\FrmSsmOrderBookSet.xaml.cs">
	    <DependentUpon>FrmSsmOrderBookSet.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\SSM\FrmSsmOrderBookPop.xaml.cs">
	    <DependentUpon>FrmSsmOrderBookPop.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\SSM\FrmSsmStatusUpdate.xaml.cs">
	    <DependentUpon>FrmSsmStatusUpdate.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\SSM\FrmSsmServiceSet.xaml.cs">
	    <DependentUpon>FrmSsmStockDtl.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\SSM\FrmSsmProfile.xaml.cs">
	    <DependentUpon>FrmSsmProfile.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\SSM\FrmSsmBookNowLst.xaml.cs">
	    <DependentUpon>FrmSsmBookNowLst.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\SSM\FrmSsmScheduleLst.xaml.cs">
	    <DependentUpon>FrmSsmScheduleLst.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\SSM\FrmSsmPaymentSet.xaml.cs">
	    <DependentUpon>FrmSsmPaymentSet.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\SSM\FrmSsmDashboardLst.xaml.cs">
	    <DependentUpon>FrmSsmDashboardLst.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\SSM\FrmSsmOrderBookLst.xaml.cs">
	    <DependentUpon>FrmSsmOrderBookLst.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>
	
	<ItemGroup>
	  <MauiXaml Update="MenuPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\Converters.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="TabBar.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="TabBarPub.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="TabItem.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ACC\FrmAccAccountLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ACC\FrmAccAccountSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ACC\FrmAccGeneralLedgerLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ACC\FrmAccPeriodLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ACC\FrmAccPeriodSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ATT\FrmATTAbsentLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ATT\FrmATTAbsentSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ATT\FrmATTEarlyOutRequestLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ATT\FrmATTEarlyOutRequestSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ATT\FrmATTEffectivePopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ATT\FrmATTEmployeeInOutLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ATT\FrmATTEmployeeInOutSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ATT\FrmATTEmployeeLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ATT\FrmATTEmployeeScheduleLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ATT\FrmATTEmployeeSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ATT\FrmATTEmployeeShiftPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ATT\FrmATTExemptionPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ATT\FrmATTLateRequestLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ATT\FrmATTLateRequestSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ATT\FrmATTLeaveRequestLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ATT\FrmATTOndutyLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ATT\FrmATTOndutySet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ATT\FrmATTOTRequestLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ATT\FrmATTOTRequestSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ATT\FrmATTTypePopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtAgendaLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtAgendaSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtBookmarkLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtBookmarkSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtCallLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtCallMediaLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtCallMediaSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtCallSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtChatLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtChatMediaLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtChatMediaSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtChatSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtContactLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtContactSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtDocLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtDocSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtMeetingLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtMeetingSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtMentionLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtMentionSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtNoteLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtNoteSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtParticipantLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtParticipantSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtScheduleLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtScheduleSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtVBoardLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CHT\FrmChtVBoardSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CRM\FrmCrmCustomerLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CRM\FrmCrmCustomerSupportLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CRM\FrmCrmEvaluationPeriodLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CRM\FrmCrmEvaluationPeriodSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CRM\FrmCrmEvaluationSummaryLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CRM\FrmCrmProjectLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CRM\FrmCrmReleaseLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CRM\FrmCrmTicketLogLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CRM\FrmCrmTicketLogSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CRM\FrmCrmUserGuideLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\ChangePasswordPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\FrmAD.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\FrmADCard.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\FrmAdmin.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\FrmCheckOut.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\FrmJobCardView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\FrmLoader.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\FrmPromotion.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\FrmPromotionCard.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\FrmSeasonal.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\FrmSeasonalCard.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\FrmSignIn.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\FrmSignUp.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\FrmStock.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\FrmStockCard.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\FrmSubscriptionPayment.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\HomePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\FrmSsmItemCard.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\OptionsPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\PopCheckOut.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\PopConfirmEmailOTP.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\PopConfirmPassword.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\PopConfirmSignature.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\PopConfirmSMSOTP.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\PopConfirmYesNo.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\PopDiscussion.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\PopLiveChat.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\PopNoti.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\PopProduct.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\PopSetting.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\PopStockDetail.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Frame\PopUserProfile.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmApplicantEvaluationLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmApplicantLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmApplicantPersonalPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmApplicantSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmAppraisalLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmCertificate.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmCertificatePopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmClaimLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmClaimSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmContactPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmDailyLogLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmDailyLogSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmDiscussionLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmEducationPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmEmployeeLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmHobbyPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmInternPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmKPILst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmLanguagePopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmLeaveLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmMeetingReservationLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmMeetingReservationSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmOthereQualificationPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmPhotoPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmPunishmentLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmRewardLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmSkillPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmSocialAffairsPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmSurveyLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmTrainPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmVacancyLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HCM\FrmHcmWorkingExperiencePopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\JOB\FrmApplicantAvailabilitySet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\JOB\FrmApplicantSalarySet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\JOB\FrmJobAdviceDtl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\JOB\FrmJobAdvicePop.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\JOB\FrmJobApplicantCertificateSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SSM\FrmSsmOrderBookPop.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SSM\FrmSsmStatusUpdate.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SSM\FrmSsmServiceSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\JOB\FrmJobApplicantEducationSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\JOB\FrmJobApplicantExperienceSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\JOB\FrmJobApplicantLanguageSkillSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\JOB\FrmJobApplicantSkillSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\JOB\FrmJobCommunityLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\JOB\FrmJobCommunityPop.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\JOB\FrmJobCommunitySet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\JOB\FrmJobCompanyDtl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\JOB\FrmJobCompanyLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\JOB\FrmJobCompanyPop.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SSM\FrmSsmProfile.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\JOB\FrmJobSearchDtl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\JOB\FrmJobSearchLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\JOB\FrmJobSearchPop.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\PAY\FrmPayDataLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\PAY\FrmPayEmployeeLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\PAY\FrmPayEmployeeSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\PAY\FrmPayItemGroupPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\PAY\FrmPayOpeningPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\PAY\FrmPayRecurringPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\PAY\FrmPaySalaryLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\PAY\FrmPayScheduleLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\PAY\FrmPaySkimPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosCollectionLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosCustomerLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosInventoryEODLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosPurchaseBillingLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosPurchaseEodLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosPurchaseInvoiceLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosPurchaseLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosPurchaseOrderLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosPurchasePaymentLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosPurchaseQuotationLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosPurchaseRequestionLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosPurchaseReturnLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosSaleBiilingLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosSaleInvoiceLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosSaleInvoicePop.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosSaleInvoiceSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosSaleOrderLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosSalePaymentLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosSaleQuotationLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosSaleReturnLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosSalesEodLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosSalesLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosStockDamageLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosStockIssueLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosStockLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosStockReceivedLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosStockTransferLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\POS\FrmPosSupplierLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SSM\FrmSsmBookNowLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SSM\FrmSsmScheduleLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SSM\FrmSsmPaymentSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SSM\FrmSsmDashboardLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SSM\FrmSsmOrderBookLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SYS\FrmAccessLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SYS\FrmAccessSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SYS\FrmApiConfigLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SYS\FrmApiConfigSet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SYS\FrmCountryLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SYS\FrmCountrySet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SYS\FrmSysApiConfigLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SYS\FrmSysMyOrderLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SYS\FrmSysMyPaymentLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SYS\FrmSysMyTransactionLst.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SYS\OvaListFormCartView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

</Project>
