using System;
namespace CS.ERP_MOB.Services.SYS
{
    public class Sys_Name
    {
        public Sys_Name()
        {
        }
        #region "Frame"
        public static string wssaveRegistration = "saveRegistration";
        public static string wsgetActivationCode = "getActivationCode";
        public static string wsactivateRegistration = "activateRegistration";
        public static string wsloadSubscriber = "loadSubscriber";
        public static string wssaveSubscriber = "saveSubscriber";
        public static string wsactivateSubscriber = "activateSubscriber";
        public static string wsLogIn = "LoginMobile";
        public static string wsSaveRegistration = "saveRegistration";
        public static string wsGetActivationCode = "getActivationCode";
        public static string wsActivateRegistration = "activateRegistration";
        public static string wsLoadSubscriber = "loadSubscriber";
        public static string wsSaveSubscriber = "saveSubscriber";
        public static string wsloadSubscribe = "/loadSubscribe";
        public static string wsActivateSubscriber = "activateSubscriber";
        public static string wsSwitchProduct = "SwitchProductMobile";
        public static string wsHeartBeat = "/HeartBeat";
        public static string wsgetSamJson = "/getSamJson";
        public static string wsUpdateNoti = "UpdateNoti";
        public static string wsupdateDiscussionStatus = "updateDiscussionStatus";
        public static string wsResetPwd = "ResetPwd";
        public static string wsSearch = "/Search";
        public static string wsLoginWithFB = "/LoginWithFB";
        public static string wsLoginWithGO = "/LoginWithGo";
        public static string wsrunQuery = "/runQuery";
        public static string wsrunVersion = "/runVersion";
        public static string wsupdateDefaultCompanyUser = "updateDefaultCompanyUser";
        public static string wsVerifyEmailOTP = "VerifyEmailOTP";
        public static string wsverifySMSOTP = "VerifySMSOTP";
        public static string wsverifyPassword = "VerifyPassword";
        public static string wsgetEmailOTP = "getEmailOTP";
        public static string wsgetSMSOTP = "getSMSOTP";
        #endregion
        #region "List"
        public static string wsgetSample = "/getSample";
        public static string wsgetAccess = "getAccess";
        public static string wsgetStatus = "/getStatus";
        public static string wsgetMenuStatus = "/getMenuStatus";
        public static string wsgetTransactionStaus = "/getStatusLst";
        public static string wsgetMenuGroup = "/getMenuGroup";
        public static string wsgetCurrency = "/getCurrency";
        public static string wsgetControlGroup = "/getControlGroup";
        public static string wsgetProduct = "/getProduct";
        public static string wsgetUserType = "/getUserType";
        public static string wsgetCountry = "getCountry";
        public static string wsgetCompanyGroup = "/getCompanyGroup";
        public static string wsgetAD = "/getAD";
        public static string wsgetBrief = "/getBrief";
        public static string wsgetControlgroup = "/getControlgroup";
        public static string wsgetDiscussionType = "/getDiscussionType";
        public static string wsgetDiscussionData = "/getDiscussionData";
        public static string wsgetDiscussion = "/getDiscussion";
        public static string wsgetMenu = "/getMenu";
        public static string wsgetSeasonalitem = "/getSeasonalitem";
        public static string wsgetState = "/getState";
        public static string wsgetTablelink = "/getTablelink";
        public static string wsgetTransactionlog = "/getTransactionlog";
        public static string wsgetUser = "/getUser";
        public static string wsgetAsk = "/getAsk";
        public static string wsgetCity = "/getCity";
        public static string wsgetCompanybranch = "/getCompanybranch";
        public static string wsgetMenuType = "/getMenuType";
        public static string wsgetTranCode = "/getTranCode";
        public static string wsGetMenu = "/getMenu";
        public static string wsGetMenuGroupJun = "/getMenuGroupJun";
        public static string wsGetMenuGroup = "/getMenuGroup";
        public static string wsgetControl = "/getControl";
        public static string wsGetControlGroupJun = "/getControlGroupJun";
        public static string wsGetControlGroup = "/getControlgroup";
        public static string wsGetUserJun = "/getUserJun";
        public static string wsGetUser = "/getUser";
        public static string wsGetPromotion = "/getPromotion";
        public static string wsGetCompany = "/getCompany";
        public static string wsGetCompanyUser = "/getCompanyUser";
        public static string wsGetSubscriberPlan = "/getSubscriberPlan";
        public static string wsGetProfileDetail = "/getProfileDetail";
        public static string wsGetSubPayment = "/getSubPayment";
        public static string wsGetNoti = "/getNoti";
        public static string wsgetTitle = "/getTitle";
        public static string wsgetGender = "/getGender";
        public static string wsgetCompanyType = "/getCompanyType";
        public static string wsgetNationality = "/getNationality";
        public static string wsgetMaritalStatus = "/getMaritalStatus";
        public static string wsgetPhotoType = "/getPhotoType";
        public static string wsgetCompanyBank = "/getCompanyBank";
        public static string wsgetTransactionLevel = "/getTransaction";
        public static string wsgetSupporting = "/getSupporting";
        public static string wsgetSupportingDay = "/getSupportingDay";
        public static string wsgetBank = "/getBank";
        public static string wsgetSubscriber = "/getSubscriber";
        public static string wsgetSubType = "/getSubType";
        public static string wsgetCustomerSupportBeat = "/getCustomerSupportBeat";
        public static string wsgetCustomerSupport = "/getCustomerSupport";
        public static string wsgetUserSupportBeat = "/getUserSupportBeat";
        public static string wsgetDiscussionService = "/getDiscussionService";
        public static string wsgetMailConfig = "/getMailConfig";
        public static string wsgetCustomerSupportUser = "/getCustomerSupportUser";
        public static string wsgetSingPostAddress = "/getSingPostAddress";
        public static string wsgetSingPost = "/getSignPost";
        public static string wsgetStockCategory = "/getCategory";
        public static string wsgetProductCompanyMail = "/getProductCompanyMail";
        public static string wsgetStockMovement = "/getStockMovement";
        public static string wsgetModule = "/getModule";
        public static string wsloadSaleTransHis =  "loadSaleTranHis";
        public static string wsgetSaleBillJun = "getSaleBillJun";
        public static string wsloadSalePayHis = "loadSalePayHis";
       
        #endregion
        #region "Save"
        public static string wsSaveCity = "/saveCity";
        public static string wsSaveAccess = "saveAccess";
        public static string wsSaveAD = "/saveAD";
        public static string wsSaveBrief = "/saveBrief";
        public static string wsSaveCompanybranch = "/saveCompanybranch";
        public static string wsSaveCompanyGroup = "/saveCompanyGroup";
        public static string wsSaveCountry = "saveCountry";
        public static string wsSaveCurrency = "/saveCurrency";
        public static string wsSaveSeasonalitem = "/saveSeasonalitem";
        public static string wsSaveState = "/saveState";
        public static string wsSaveTablelink = "/saveTablelink";
        public static string wsSaveTransactionStatus = "/saveStatus";
        public static string wsSaveUserType = "/saveUserType";
        public static string wsSaveProduct = "/saveProduct";
        public static string wsSaveDiscussion = "/saveDiscussion";
        public static string wssaveMenuType = "/saveMenuType";
        public static string wssaveTranCode = "/saveTranCode";
        public static string wsSaveDiscussionType = "/saveDiscussionType";
        public static string wsSaveMenu = "/saveMenu";
        public static string wsSaveMenuGroupJun = "/saveMenuGroupJun";
        public static string wsSaveControl = "/saveControl";
        public static string wsSaveControlGroupJun = "/saveControlGroupJun";
        public static string wsSaveUserJun = "/saveUserJun";
        public static string wsSaveUser = "/saveUser";
        public static string wsSavePassword = "savePassword";
        public static string wsSavePromotion = "/savePromotion";
        public static string wsSaveCompany = "/saveCompany";
        public static string wsSaveCompanyUser = "/saveCompanyUser";
        public static string wsSaveCustomerDetail = "/saveCustomerDetail";
        public static string wsSaveSubscriberDetail = "/saveSubscriberDetail";
        public static string wsSaveNoti = "/saveNoti";
        public static string wsSaveSubscriberPlan = "/saveSubscriberPlan";
        public static string wssaveTitle = "/saveTitle";
        public static string wssaveGender = "/saveGender";
        public static string wssaveCompanyType = "/saveCompanyType";
        public static string wssaveNationality = "/saveNationality";
        public static string wssaveMaritalStatus = "/saveMaritalStatus";
        public static string wssavePhotoType = "/savePhotoType";
        public static string wssaveCompanyBank = "/saveCompanyBank";
        public static string wssaveTransactionLevel = "/saveTransaction";
        public static string wssaveSupporting = "/saveSupporting";
        public static string wssaveSupportingDay = "/saveSupportingDay";
        public static string wssaveBank = "/saveBank";
        public static string wssaveSubType = "/saveSubType";
        public static string wssaveCustomerSupport = "/saveCustomerSupport";
        public static string wssaveCustomerSupportData = "/saveCustomerSupportData";
        public static string wssaveUserSupport = "/saveUserSupport";
        public static string wssaveUserSupportData = "/saveUserSupportData";
        public static string wssaveVisitor = "/saveVisitor";
        public static string wssaveDiscussionService = "/saveDiscussionService";
        public static string wssaveVersionControl = "/saveVersionControl";
        public static string wssaveMailConfig = "/saveMailConfig";
        public static string wssaveCustomerSupportUser = "/saveCustomerSupportUser";
        public static string wssaveSingPost = "/saveSignPost";
        public static string wsSaveCategory = "/saveCategory";
        public static string wssaveProductCompanyMail = "/saveProductCompanyMail";
        public static string wssaveStockMovement = "/saveStockMovement";
        public static string wssaveModule = "/saveModule";
        #endregion
        #region "Load"
        public static string wsLoadCity = "/loadCity";
        public static string wsLoadState = "/loadState";
        public static string wsLoadMenu = "/loadMenu";
        public static string wsLoadMenuGroup = "/loadMenuGroup";
        public static string wsLoadControl = "/loadControl";
        public static string wsLoadControlGroup = "/loadControlGroup";
        public static string wsLoadUser = "/loadUser";
        public static string wsLoadPromotion = "/loadPromotion";
        public static string wsLoadCompany = "/loadCompany";
        public static string wsLoadCompanyUser = "/loadCompanyUser";
        public static string wsLoadSubscriberPlan = "/loadSubscriberPlan";
        public static string wsLoadProfile = "/loadProfile";
        public static string wsLoadNoti = "/loadNoti";
        public static string wsLoadCompanyBank = "/loadCompanyBank";
        public static string wsloadVersionControl = "/loadVersionControl";
        public static string wsloadCustomerSupportUser = "/loadCustomerSupportUser";
        public static string wsLoadCategory = "/loadCategory";
        public static string wsloadProductCompanyMail = "/loadProductCompanyMail";
        public static string wsloadStockMovement = "/loadStockMovement";
        #endregion
    }
}

